import Head from 'next/head';
import axios from 'axios';
import Home from '@/pages/home';

export default function Index({ categoryList }) {
	return (
		<>
			<Head>
				<title>App</title>
				<meta name="description" content="Generated by create next app" />
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Home categoryList={categoryList} />
		</>
	);
}

export const getServerSideProps = async (context) => {
	try {
		const response = await axios.get(
			`${process.env.NEXT_PUBLIC_API_URL}/categories`
		);
		return {
			props: {
				categoryList: response.data.data ?? [],
			},
		};
	} catch (error) {
		console.log(error);
	}
};
