import Header from '@/components/layout/header/Header';
import Head from 'next/head';
import { Provider } from 'react-redux';
import store from 'redux/store';
import Home from '@/pages/home';

export default function Index() {
	return (
		<>
			<Head>
				<title>App</title>
				<meta name="description" content="Generated by create next app" />
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Provider store={store}>
				<Header />
				<Home />
			</Provider>
		</>
	);
}
